#Allows creating a release by pushing a tag
#This might be useful for retroactive releases
name: Draft release from git tag

on:
  push:
    tags: "*"

jobs:
  draft:
    name: Create GitHub draft release
    if: "startsWith(github.event.head_commit.message, 'Release ')"
    uses: ./.github/workflows/draft-release.yml
